services:
  app:
    build:
      dockerfile: Dockerfile
      target: development
    image: local/squire/app
    volumes:
      - ..:/var/www/html
    # Linux only
#    extra_hosts:
#      - host.docker.internal:host-gateway
  web:
    image: node:10
    user: node
    working_dir: /home/node/app
    volumes:
      - ..:/home/node/app
      - ./web.sh:/web.sh
    entrypoint: "/web.sh"
    ports:
      - 80:80
      - 3001:3001
    environment:
      - APP_HOST=app:8000
      - WEB_PORT=80
  database:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=VerySecretPassword
      - MYSQL_DATABASE=squire
      - MYSQL_USER=squire
      - MYSQL_PASSWORD=DevelopmentPassword
    volumes:
      - ./DBInitialize.sql:/docker-entrypoint-initdb.d/init.sql

networks:
  default:
    name: squire
    driver: bridge

name: squire
