services:
  web:
    build:
      dockerfile: Dockerfile
      target: development
    ports:
      - "80:8000"
    volumes:
      - ..:/var/www/html
    networks:
      default:
        aliases:
          - squire-web
  database:
    image: mysql:5.6
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=VerySecretPassword
      - MYSQL_DATABASE=squire
      - MYSQL_USER=squire
      - MYSQL_PASSWORD=DevelopmentPassword
    networks:
      default:
        aliases:
          - squire-database

networks:
  default:
    name: squire
    driver: bridge
