services:
  web:
    build:
      dockerfile: Dockerfile
      target: development
    image: squire-web
    ports:
      - "80:8000"
    volumes:
      - ..:/var/www/html
    container_name: squire-web
  database:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=VerySecretPassword
      - MYSQL_DATABASE=squire
      - MYSQL_USER=squire
      - MYSQL_PASSWORD=DevelopmentPassword
    container_name: squire-database
    volumes:
      - ./DBInitialize.sql:/docker-entrypoint-initdb.d/init.sql

networks:
  default:
    name: squire
    driver: bridge
